#ifndef COMMON_H
#define COMMON_H

#define GPIO_EYES		PB0
#define GPIO_SERVO1		PB1
#define GPIO_SERVO2		PB2
#define GPIO_WT588_BUSY		PB6

#define GPIO_BATTERY_SENSE	PC5

#define GPIO_RIGHT_REPULSOR	PD1
#define GPIO_OPEN_HELMET	PD2
#define GPIO_SHOT_REPULSOR	PD3
#define GPIO_LEFT_REPULSOR	PD4
#define GPIO_WT588_RESET	PD6
#define GPIO_WT588_DATA		PD7

#endif // COMMON_H
