#ifndef VOICE_H
#define VOICE_H

enum {
	SOUND_IM_SUIT_01 = 0,
	SOUND_IM_SUIT_02,
	SOUND_IM_SUIT_03,
	SOUND_IM_SUIT_04,
	SOUND_IM_SUIT_05,
	SOUND_IM_SUIT_06,
	SOUND_IM_SUIT_07,
	SOUND_JARVIS_ARC_REACTOR_MODE,
	SOUND_JARVIS_BATTERY_FULL_1,
	SOUND_JARVIS_BATTERY_FULL_2,
	SOUND_JARVIS_BATTERY_FULL_3,
	SOUND_JARVIS_BATTERY_LOW_1,
	SOUND_JARVIS_BATTERY_LOW_2,
	SOUND_JARVIS_BATTERY_LOW_3,
	SOUND_JARVIS_EARLY_TO_RISE,
	SOUND_JARVIS_EVENING,
	SOUND_JARVIS_FULL_ARMOR_MODE,
	SOUND_JARVIS_HALLOWEEN,
	SOUND_JARVIS_REPULSOR_POWERED,
	SOUND_JARVIS_RISE_AND_SHINE,
	SOUND_JARVIS_SCREEN_ON,
	SOUND_JARVIS_TIME_TO_GET_UP_SLEEPY,
	SOUND_JARVIS_WEATHER_HOT,
	SOUND_REPULSOR
};

void voice_init(void);

void voice_play(int sound);
uint8_t voice_is_busy(void);

#endif // VOICE_H
