#ifndef VOICE_H
#define VOICE_H

enum {
	IM_SUIT_01 = 0,
	IM_SUIT_02,
	IM_SUIT_03,
	IM_SUIT_04,
	IM_SUIT_05,
	IM_SUIT_06,
	IM_SUIT_07,
	JARVIS_ARC_REACTOR_MODE,
	JARVIS_BATTERY_FULL_1,
	JARVIS_BATTERY_FULL_2,
	JARVIS_BATTERY_FULL_3,
	JARVIS_BATTERY_LOW_1,
	JARVIS_BATTERY_LOW_2,
	JARVIS_BATTERY_LOW_3,
	JARVIS_EARLY_TO_RISE,
	JARVIS_EVENING,
	JARVIS_FULL_ARMOR_MODE,
	JARVIS_HALLOWEEN,
	JARVIS_REPULSOR_POWERED,
	JARVIS_RISE_AND_SHINE,
	JARVIS_SCREEN_ON,
	JARVIS_TIME_TO_GET_UP_SLEEPY,
	JARVIS_WEATHER_HOT,
	REPULSOR
};

void voice_init(void);

void voice_play(int sound);
uint8_t voice_is_busy(void);

#endif // VOICE_H
